[package]
name = "mochi-compiler"
version = "0.1.0"
authors = ["Michael Zhang <iptq@protonmail.com>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
lalrpop = "0.16"

[dependencies]
lalrpop-util = "0.16"
regex = "1.0"
