[package]
name = "mochic"
version = "0.1.0"
authors = ["Michael Zhang <iptq@protonmail.com>"]
edition = "2018"

[dependencies]
codespan = "0.2"
codespan-reporting = "0.2"
mochi = { path = "..", features = ["codegen"] }
structopt = "0.2"
